### ISSUE TITLE
Add is_canceled or similar method to oneshot Sender

### ISSUE THREAD

**Issue by seanmonstar** [alexcrichton/futures-rs#317]
There currently exists `tx.poll_cancel()`, but this will register the current task with the oneshot, such that it will be unparked once the `oneshot::Receiver` is dropped. This may be undesirable, as the current task may not want to wait on the oneshot, but instead chose to use it immediately, or drop it. 

The current behavior will even unpark the current task after a successful call to `complete`, since the `poll_cancel` will store the current task in the `tx_task` slot. After successfully completing and dropping the sender, and afterwards the receiver waking and taking the message, the drop of the receiver will unconditionally wake any task waiting in the `tx_task`.

It seems desirable (at least I have a use case, I'm assuming others would also) to be able to just check a `bool`, and either send or drop and do something else. Such as:

```rust
if let Some(tx) = self.waiting.take() {
    if !tx.is_canceled() {
        tx.complete(thingy);
        return;
    }
}
// else
self.holding = Some(thingy);
```

**Comment by alexcrichton** [comment]
> The current behavior will even unpark the current task after a successful call to `complete`

It sounds like the crux of this issue boils down to this property, no? This is just a bug that should be fixed, and if fix would a `is_canceled` method still be motivated?

**Comment by seanmonstar** [comment]
With the bug fixed, some cycles are saved, which would be great. However, it's still kind of unwieldy to turn the `Poll` into a boolean check, and it's slightly confusing, since the `Async` enum doesn't easily translate to the question "does the Sender still exist?" I understand what it currently means, that `Ready` implies the `Receiver` is done, but you could also see how someone would assume `Ready` means the `Receiver` is ready to receive.

For a few reasons, I ended up making a small crate similar to oneshot, without the `Send` bounds, and changed having a `poll_cancel()` method into being able to convert the `Sender` into a `Future`. So there is both `tx.is_canceled()`, and `tx.waiting().and_then(whatever)`: https://docs.rs/relay/0.1.0/relay/struct.Sender.html

**Comment by alexcrichton** [comment]
Hm I'm sort of confused:

* Why does `poll_cancel` returning `Async` make you think it would connect to the receiver being able to receive?
* What `Send` bounds are you thinking of? AFAIK there are none on `oneshot` except its own `Send` and `Sync` impls

We could certainly add an adapter to change `poll_cancel` to a future! I'm not sure how useful that would be though? Once you do that conversion it seems like it'd be much harder to get access to it to send a value. Similarly the `poll_fn` future may help here?

**Comment by seanmonstar** [comment]
- I don't understand your question. `Sender.poll_cancel` returns a value depending on whether the `Receiver` has been dropped, right?
- I didn't mean that `oneshot` doesn't work without a `Send` value. I meant I didn't need my channel to be send at all, so I just built one that skipped the atomic operations, and it's a little faster for it, is all. But I also added a `is_canceled` method to my `Sender`, and found it useful even though there is a `Future` adapter.

I just felt like `poll_cancel` was trying to be both an `is_canceled` and a `Future` in one method, but had downsides in both cases, and so it seemed better to split the two concerns.

**Comment by alexcrichton** [comment]
Hm ok, so taking [your response from before](https://github.com/alexcrichton/futures-rs/issues/317#issuecomment-269888746):

> However, it's still kind of unwieldy to turn the Poll into a boolean check

Yes and we should change this to `Async` as conventions have changed over time since the method was first added.

> it's slightly confusing, since the Async enum doesn't easily translate to the question "does the Sender still exist?"

I'm not sure what you mean here. If you call `Sender::poll_cancel` then the `Sender` exists because you're calling a method on it?

> you could also see how someone would assume Ready means the Receiver is ready to receive.

I didn't understand how this conception would happen. A function called `poll_cancel` returned "ready". Why would that translate to "oh the receiver can receive now" when cancellation is defined as "the receiver is gone".

---

The `poll_cancel` method is indeed a future and a `is` question in the same method. That's because any other construction is racy in most situations.

**Comment by seanmonstar** [comment]
> We should change this to Async as conventions have changed over time since the method was first added.

That does make it easier to turn in to a `tx.poll_cancel().is_ready()`.

> I'm not sure what you mean here. If you call Sender::poll_cancel then the Sender exists because you're calling a method on it?

Woops, I meant "does the Receiver still exist?"

Here is how I read it and was left confused:

- `tx.poll_cancel() == Ok(Async::Ready(()))` could mean that some `Cancel` event happened, since `poll_cancel` is asking "Let me know (poll) when 'cancel' is done (ready)".
- `tx.poll_cancel() == Ok(Async::Ready(()))` could mean that the Receiver is still 'ready'. While maybe not the first thing you think of, I thought of both of these when reading the method signature and so was confused.

Perhaps returning an `Async<Canceled>` would make it more clear (`Canceled` already exists as the `Err` case on `rx.poll`). `tx.poll_cancel() == Async::Ready(Canceled)` is clearer that  a `Canceled` event occurred. It's still my personal opinion that it's is *less* clear than if the intents were separated into two separate methods, but opinions opinions...

----

>  That's because any other construction is racy in most situations.

If using `poll_cancel` as an `is` question, the same racyness exists, since it could be canceled in between the `poll_cancel` and the `complete` calls. Using `poll_cancel` however will mean additionally that the `Sender` parks the current `Task`, when I may not have needed that (I realize that just means a clone, but still).

It seems like a separate `atomic_complete` method would be needed to not be racy, or alternatively change the return type of `complete` to be `Result<(), T>`.
